export const CURRICULUM = {
  "MATH 111": "Differential Calculus",
  "CHEM LEC 111": "Chemistry for Engineers (Lecture)",
  "CHEM LAB 111": "Chemistry for Engineers (Laboratory)",
  "MATH 122": "Integral Calculus",
  "PHYS 121": "Physics for Engineers",
  "MATH 213": "Differential Equations",
  "MECH 211": "Statics of Rigid Bodies",
  "SURV 211": "Fundamentals of Surveying",
  "ECON 211": "Engineering Economics",
  "MNGT 211": "Engineering Management",
  "MATH 224": "Engineering Data Analysis",
  "MECH 222": "Dynamics of Rigid Bodies",
  "CE 221": "Mechanics of Deformable Bodies",
  "CE 223": "Construction Materials and Testing",
  "TECHNO 101": "Technopreneurship 101",
  "CE 311": "Structural Theory",
  "CE 312": "Highway and Railroad Engineering",
  "CE 313": "Engineering Utilities 1",
  "CE 314": "Engineering Utilities 2",
  "CE 315": "Numerical Solutions to CE Problems",
  "CE 322": "Building System Design",
  "CE 323": "CE Laws, Ethics and Standards",
  "CE 324": "Hydrology",
  "CE 325": "Hydraulics",
  "CE 326": "Principles of Steel Design",
  "CE 327": "Principles of Reinforced Concrete",
  "CE 411": "Geotechnical Engineering",
  "CE 412": "Principles of Transportation Engineering",
  "CE 413": "CE Project 1",
  "CE 414": "Quantity Surveying",
  "PC 411": "Specialization 1",
  "PC 412": "Specialization 2",
  "CE 421": "CE Project 2",
  "CE 422": "Construction Methods & Project Management",
  "PC 421": "Specialization 3",
  "PC 422": "Specialization 4",
  "PC 423": "Specialization 5",
}
